### ISSUE TITLE
Che 7 docs overview

### ISSUE THREAD

**Issue by rkratky** [eclipse/che-docs#712]
This issue collects all progress info about the ongoing 'Che 7 docs' task. Use the outline below to identify topics that still need to be:

* adapted from Che 6 docs, or
* developed from scratch

Items that have been checked off are merged to the che-docs master and published. They may still need improvements, and they may still contain TODO references. 

Process:

1. Pick an item (from the unchecked ones) for you (your team) to work on.
2. File a separate issue for it in this repo.
    * Identify content from Che 6 docs that can be reused to satisfy the requirement for this item, and tag the docs team to make it happen (providing info about things that might need to be updated/modified), or
    * Write the new docs in a manner that suits you, and tag the docs team to review and import the content into this repo.
3. Submit a PR; when merged, the item will be checked off in this list.

* [x] Overview
  * [x] Introduction to Eclipse Che
    * [x] Introductory videos
    * [x] Features and benefits
  * [x] Che quick-starts
    * [x] Running Che locally
    * [ ] 🔥Running Che remotely
    * [ ] Navigating Che using the Dashboard
    * [ ] Using the IDE
  * [x] 🔥Hosted Che https://github.com/eclipse/che-docs/issues/715
  * [ ] 🔥Che architecture
    * [ ] Types of plug-ins https://github.com/eclipse/che-docs/issues/716
    * [ ] Plug-in registry https://github.com/eclipse/che-docs/issues/716
    * [ ] Plugin brokers https://github.com/eclipse/che-docs/issues/717
......
* [x] End-User Guide
  * [ ] Che-Theia IDE basics
    * [ ] Navigating the Che-Theia user interface
    * [ ] Files and projects
    * [ ] Editing code and code assistance
    * [ ] Key bindings
    * [ ] Searching
    * [ ] 🔥Commands
    * [ ] Debugging
    * [ ] Testing
    * [ ] 🔥Version control
    * [ ] Integrated terminal
    * [ ] Languages
    * [ ] SSH
  * [x] Using developer environments - workspaces
    * [x] Workspaces overview
    * [ ] Defining workspaces
      * [ ] Configuring runtimes
      * [ ] Exposing services
      * [ ] Mounting specific volumes into workspaces
      * [ ] Setting environment variables
      * [ ] Configuring projects
    * [x] 🔥Making a workspace portable using a Devfile
      * [x] 🔥Using a Devfile
      * [x] 🔥Creating your own Devfile
        * [x] 🔥Adding projects
        * [x] 🔥Adding components
          * Plugins
          * Containers
          * Kubernetes resources
       * [x] 🔥Adding commands
       * [x] 🔥Using different plugin registries
      * [ ] 🔥External resources
       * [ ] 🔥Examples
       * [x] 🔥Devfile specification reference
    * [ ] 🔥Migrating an old Che 6 workspace
    * [ ] Using and customizing a workspace template - stack
    * [ ] Exporting a workspace with a Che factory
    * [ ] Sharing access to a workspace
  * [x] Extending Che
    * [x] What is a Che-Theia plug-in
       * [x] Che-Theia plug-in concept in detail
       * [x] Che-Theia plug-in metadata
       * [x] Che-Theia plug-in lifecycle
       * [x] Embedded and remote Che-Theia plug-ins
    * [x] Developing Che-Theia plug-ins
       * [x] Che-Theia plug-in development flow
       * [x] Bootstrapping Che-Theia plug-in development with Yeoman
       * [x] Developing Che-Theia plug-ins using Che
       * [x] Converting a Visual Studio Code extension to a Che-Theia plug-in
       * [x] Developing a real world Che-Theia plug-in
       * [x] Developing a real world plug-in for Che
    * [x] Testing Che-Theia plug-ins
    * [x] Publishing Che-Theia plug-ins
       * [x] Che-Theia plug-in registries
       * [x] Adding a Che-Theia plug-in to the Che plug-in registry
       * [x] Adding a Che-Theia plug-in into a workspace
       * [x] Sharing your Che-Theia plug-in with a factory
       * [x] Overriding RAM of a Che-Theia plug-in
    * [x] Using alternative IDEs in Che
    * [x] Che extensibility reference
       * [x] Che extension points
       * [x] Che-Theia plug-in API
       * [ ] Language Server Protocol
       * [ ] Debug Adapter Protocol
       * [x] Architectural insights about the plugin brokers
  * [ ] API reference
    * [ ] Access to Swagger
    * [ ] Workspace API
    * [ ] Permissions API
    * [ ] Factory API
    * [ ] Resources API
    * [ ] IDE macros
  * [ ] Troubleshooting for Che end users

......
* [ ] Installation Guide
  * [ ] Che installation overview
    * [ ] Target platforms
    * [ ] Deployment architecture diagram
  * [ ] Che installation prerequisites
    * [ ] Storage
    * [ ] Networking
    * [ ] Identity
  * [ ] Installing Che on different Kubernetes distributions
  * [ ] Updating Che
  * [ ] Advanced configuration options
    * [ ] Che configuration reference table
    * [ ] Deploying Che with HTTPS mode
    * [ ] Deploying Che without Keycloak
    * [ ] Configuring Che Persistent Volumes strategy
    * [ ] Configuring Che with and without Keycloak
    * [ ] Configuring private Docker registries
    * [ ] Configuring email notifications
    * [ ] Configuring namespace strategies
    * [ ] Configuring workspace memory settings
    * [ ] Configuring Che with OpenShift OAuth
  * [ ] Troubleshooting Che installation

......
* [x] Administration Guide
  * [ ] Administration tasks
    * [ ] Removing user data
    * [ ] 🔥Retrieving Che logs
       * Server
       * Plugin Broker
       * Workspaces
          * Theia
           * Language Servers
     * [ ] 🔥Devfile registry customization
     * [ ] 🔥Plugin registry customization
  * [x] Monitoring Che
    * [x] Understanding Che monitoring stack structure
    * [x] Collecting Che metrics with Prometheus
    * [x] Viewing Che metrics on Grafana dashboards
    * [x] Developing Grafana dashboards
    * [x] Extending Che monitoring metrics
  * [x] Tracing Che
    * [x] Enabling Che metrics collections
    * [x] Viewing Che traces on Jaeger UI
    * [x] Che tracing codebase overview and extension guide
  * [x] 🔥Securing Che
    * [ ] Che security overview
    * [ ] 🔥User authentication and authorization
    * [ ] 🔥Using GitHub OAuth
    * [ ] Permission model overview
  * [ ] Troubleshooting for Che administrators

......
* [ ] Hands-On Guidance
  * [ ] Tips and tricks for Che
  * [ ] Che FAQ
  * [ ] End-user tasks
    * [ ] 🔥Creating a workspace from code sample
    * [ ] 🔥Creating a workspace by importing source code of your project
    * [ ] 🔥Importing a Kubernetes application into a Che workspace
    * [ ] 🔥Using a Visual Studio Code extension in Che
    * [ ] Configuring plug-ins
    * [ ] 🔥Remotely accessing your workspace (open a shell)
    * [ ] Configuring your VCS credentials for your workspaces
    * [ ] 🔥Use an alternative Che workspace editor
  * [ ] Contributor tasks
    * [ ] Developing your first plug-in
    * [ ] Adding support for a new language #718 
    * [x] Adding support for a new debugger #719 
    * [ ] Packaging a Visual Studio Code plug-in for Che
    * [ ] Providing a custom IDE based on Eclipse Theia
    * [ ] Switching the default editor to another one

**Comment by l0rd** [comment]
@rkratky @slemeur I have added a 🔥 close to the sections that are mandatory for the GA

**Comment by themr0c** [comment]
No need to keep this issue open.
